# Generated by Django 5.0.6 on 2024-06-03 05:16

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(verbose_name=255)),  # type: ignore[arg-type]  # noqa: E501
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("disabled_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "client_type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="assets.clienttype",
                    ),
                ),
                (
                    "country_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="assets.country",
                    ),
                ),
            ],
        ),
    ]
