# Generated by Django 5.0.6 on 2024-06-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mega_ai_client", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_name",
            field=models.CharField(max_length=255),
        ),
    ]
