# Generated by Django 5.0.6 on 2024-06-05 15:17

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
        ("mega_ai_client", "0002_alter_client_client_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="disabled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ActionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_destination_details", models.CharField(max_length=255)),
                ("action_connection_details", models.CharField(max_length=255)),
                ("action_response_log_details", models.TextField(max_length=255)),
                ("description", models.TextField(max_length=255)),
                (
                    "action_type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assets.actiontype",
                    ),
                ),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mega_ai_client.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClientModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mega_ai_client.client",
                    ),
                ),
                (
                    "module_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="assets.module"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClientSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.IntegerField()),
                ("next_billing_date", models.DateTimeField()),
                ("comments", models.TextField(max_length=255)),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mega_ai_client.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoalType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goal_type_name", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=255)),
                (
                    "module_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="assets.module"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoalDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goal_reached_when", models.CharField(max_length=100)),
                ("special_goals_logic", models.CharField(max_length=255)),
                ("comments", models.TextField(max_length=255)),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mega_ai_client.client",
                    ),
                ),
                (
                    "goal_type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mega_ai_client.goaltype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=255)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mega_ai_client.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_details", models.TextField(max_length=255)),
                ("description", models.TextField(max_length=255)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 6, 5, 15, 17, 20, 14774)
                    ),
                ),
                ("updated_at", models.DateTimeField()),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mega_ai_client.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=50)),
                ("user_email", models.CharField(max_length=50)),
                ("password_hash", models.CharField(max_length=255)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 6, 5, 15, 17, 20, 13276)
                    ),
                ),
                ("updated_at", models.DateTimeField()),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mega_ai_client.client",
                    ),
                ),
                (
                    "country_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="assets.country"
                    ),
                ),
                (
                    "role_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="assets.role"
                    ),
                ),
                (
                    "user_type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assets.clienttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VirtualAgentDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_ref_id", models.CharField(max_length=50)),
                ("external_bot_id", models.CharField(max_length=50)),
                ("external_ref_details", models.CharField(max_length=255)),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mega_ai_client.client",
                    ),
                ),
                (
                    "virtual_agent_type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assets.virtualagenttype",
                    ),
                ),
            ],
        ),
    ]
