# Generated by Django 5.0.6 on 2024-06-05 15:20

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mega_ai_client",
            "0003_alter_client_disabled_at_actiondetail_clientmodule_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 5, 15, 20, 28, 534906)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 5, 15, 20, 28, 533399)
            ),
        ),
    ]
