name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  AZURE_CONTAINER_REGISTRY_USERNAME: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
  AZURE_CONTAINER_REGISTRY_PASSWORD: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run security checks
        run: |
          bandit -r app.py

  build-and-push:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get repository name
        id: repo-name
        run: echo "::set-output name=repo::$(basename $GITHUB_REPOSITORY)"

      - name: Set up build environment variables
        id: vars
        run: |
          TIMESTAMP=$(date -u +"%Y%m%d%H%M%S")
          SHORT_SHA=$(git rev-parse --short HEAD)
          IMAGE_NAME="${{ steps.repo-name.outputs.repo }}"
          IMAGE_TAG="$SHORT_SHA-$TIMESTAMP"
          echo "::set-output name=image_name::$IMAGE_NAME"
          echo "::set-output name=image_tag::$IMAGE_TAG"
        shell: bash

      - name: Log in to Azure Container Registry
        run: |
          echo ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }} | docker login ${{ secrets.AZURE_CONTAINER_REGISTRY }} -u ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ steps.vars.outputs.image_name }}:${{ steps.vars.outputs.image_tag }} .

      - name: Push Docker image to ACR
        run: |
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ steps.vars.outputs.image_name }}:${{ steps.vars.outputs.image_tag }}
